Repository ucsb-cs156-f24/proj-dining-f24-14, pull requests merged in 2024-11, with the labels that each got.

#53 Implemented database for reviews
  src/main/java/edu/ucsb/cs156/dining/entities/Reviews.java
  src/main/java/edu/ucsb/cs156/dining/repositories/ReviewsRepository.java
  src/main/resources/db/migration/changes/Reviews.json
Labels: 5, Merge Candidate-CI

#58 Create placeholder page for individual dining commons
  frontend/src/App.js
  frontend/src/main/pages/Dining/DiningCommonsIndexPage.js
  frontend/src/tests/pages/Dining/DiningCommonsIndexPage.test.js
  src/main/resources/application.properties
Labels: 5, Merge Candidate-CI

#64 Add DiningCommonsTable to HomePage, update HomePage tests, and HomePage Storybook
  frontend/src/main/pages/HomePage.js
  frontend/src/stories/pages/HomePage.stories.js
  frontend/src/tests/pages/HomePage.test.js
Labels: 5, Merge Candidate-CI

#65 Menu Display Frontend 1: MealsTable
  frontend/src/fixtures/mealsFixtures.js
  frontend/src/main/components/DiningCommons/MealsTable.js
  frontend/src/stories/components/DiningCommons/MealsTable.stories.js
  frontend/src/tests/components/DiningCommons/MealsTable.test.js
Labels: 10, Merge Candidate-CI

#68 Create Table Component for MyReviews - Reviews Frontend 2
  frontend/src/fixtures/myReviewsFixtures.js
  frontend/src/main/components/MyReviews/MyReviewsTable.js
  frontend/src/main/utils/MyReviewsUtils.js
  frontend/src/stories/components/MyReviews/MyReviewsTable.stories.js
  frontend/src/tests/components/MyReviews/MyReviewsTable.test.js
  frontend/src/tests/utils/MyReviewsUtils.test.js
Labels: 10, Merge Candidate-CI

#56 Create a DiningCommonsService and related controller method for fetching the names of all dining commons
  src/main/java/edu/ucsb/cs156/dining/controllers/DiningCommonsController.java
  src/main/java/edu/ucsb/cs156/dining/services/DiningCommonsService.java
  src/test/java/edu/ucsb/cs156/dining/controllers/DiningCommonsControllerTests.java
  src/test/java/edu/ucsb/cs156/dining/services/DiningCommonsServiceTests.java
  src/test/java/edu/ucsb/cs156/dining/web/HomePageWebIT.java
Labels: 10, Merge Candidate-CI

#61 Menu Display Backend 1: Meals Endpoint
  src/main/java/edu/ucsb/cs156/dining/controllers/DiningCommonsController.java
  src/main/java/edu/ucsb/cs156/dining/controllers/UCSBDiningCommonsController.java
  src/main/java/edu/ucsb/cs156/dining/services/DiningCommonsService.java
  src/test/java/edu/ucsb/cs156/dining/controllers/DiningCommonsControllerTests.java
  src/test/java/edu/ucsb/cs156/dining/services/DiningCommonsServiceTests.java
Labels: 10

#67 Add placeholder page /moderate accessible only to admins and link in menu bar as "Moderate"
  frontend/src/App.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/pages/ModeratePage.js
  frontend/src/tests/components/Nav/AppNavbar.test.js
  frontend/src/tests/pages/ModeratePage.test.js
Labels: 5, Merge Candidate-CI

#62 Menu Display Backend 2: Menus Endpoint
  src/main/java/edu/ucsb/cs156/dining/controllers/DiningCommonsController.java
  src/main/java/edu/ucsb/cs156/dining/services/DiningCommonsService.java
  src/test/java/edu/ucsb/cs156/dining/controllers/DiningCommonsControllerTests.java
  src/test/java/edu/ucsb/cs156/dining/services/DiningCommonsServiceTests.java
Labels: 10, Merge Candidate-CI

#69 MenuItem Placeholder Page
  frontend/src/App.js
  frontend/src/main/pages/MenuItemPage.js
  frontend/src/tests/pages/MenuItemPage.test.js
Labels: 5, Merge Candidate-CI

#63 Menu Display Backend 3: Modify menus endpoint and implement MenuItem database
  pom.xml
  src/main/java/edu/ucsb/cs156/dining/controllers/DiningCommonsController.java
  src/main/java/edu/ucsb/cs156/dining/entities/MenuItem.java
  src/main/java/edu/ucsb/cs156/dining/repositories/MenuItemRepository.java
  src/main/java/edu/ucsb/cs156/dining/services/DiningCommonsService.java
  src/main/resources/db/migration/changes/MenuItems.json
  src/test/java/edu/ucsb/cs156/dining/controllers/DiningCommonsControllerTests.java
  src/test/java/edu/ucsb/cs156/dining/services/DiningCommonsServiceTests.java
Labels: 10, Ready-For-Staff, Merge Candidate-CI
